version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=cell_user
      - POSTGRES_DB=cell_db

  db:
    build: ./containers/db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb-postgis.sql:/docker-entrypoint-initdb.d/initdb-postgis.sql
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=cell_user
      - POSTGRES_DB=cell_db
volumes:
  db: {}
